### PR TITLE
Extending support for IExplorer 11

### PR DESCRIPTION
**Pull request by vhuerta**
I have a react app using es modules and for all the browsers it was working fine except for iexplorer 11 in which I was getting `Syntax error` digging into the bundle found that arrow functions weren't transpiled also I had to disable `esmodules` target and now is working fine, hope it helps!

### CODE REVIEW

**Comment by roderickhsiao** [comment]
Thanks for the PR, the idea is that this library start to compile just es module, and if your app needs to support older browser (such as IE 11), you can add the module in your build target

assuming we are using webpack here, target browser includes IE 11 (babel-preset-env), you could include `react-in-viewport` in your `babel-loader` (most of us excludes all node_modules) compile. 
```
{
        test: /\.(js|jsx|mjs)$/,
        loader: 'babel-loader',
        include: [your source folder]
          .concat(path for node_module/react-in-viewport)
      }
```

The reason behinds that is when browser support getting better, the app could deliver the smallest bundle by itself depends on the supported browser matrix, and library just delivery the most efficient one .

See https://github.com/roderickhsiao/react-in-viewport/issues/22

**Comment by perrin4869** [comment]
Hm... Any solution for `create-react-app` users? I'd prefer not to eject just in order to be able to use this lib

**Comment by roderickhsiao** [comment]
@perrin4869 doesn't create-react-app already support es6 in node_modules in 2.x version?
https://github.com/facebook/create-react-app/issues/3889#issuecomment-359289166 

I didn't use create-react-app for production app, but could definitely try and test it out

**Comment by perrin4869** [comment]
Hm... Yeah seems that's the case

**Comment by roderickhsiao** [comment]
As Microsoft is dropping IE, I'm closing this

**Pull request closed without merging**
